resolver: lts-18.27
allow-newer: true

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'

extra-deps:
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- smtlib-backends-0.3
- smtlib-backends-z3-0.3
- smtlib-backends-process-0.3

nix:
  packages: [z3]

extra-include-dirs:
- /usr/local/Homebrew/Cellar/z3/4.12.2/include
extra-lib-dirs:
- /usr/local/Homebrew/Cellar/z3/4.12.2/lib
